/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as DnaRouteImport } from './routes/dna'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as HolographyRouteImport } from './routes/holography'
import { Route as LabRouteImport } from './routes/lab'
import { Route as LatticeRouteImport } from './routes/lattice'
import { Route as MethodRouteImport } from './routes/method'
import { Route as StopRouteImport } from './routes/stop'
import { Route as SymmetryRouteImport } from './routes/symmetry'
import { Route as NSlugRouteImport } from './routes/n.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DnaRoute = DnaRouteImport.update({
  id: '/dna',
  path: '/dna',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const HolographyRoute = HolographyRouteImport.update({
  id: '/holography',
  path: '/holography',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LatticeRoute = LatticeRouteImport.update({
  id: '/lattice',
  path: '/lattice',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const StopRoute = StopRouteImport.update({
  id: '/stop',
  path: '/stop',
  getParentRoute: () => rootRouteImport,
} as any)
const SymmetryRoute = SymmetryRouteImport.update({
  id: '/symmetry',
  path: '/symmetry',
  getParentRoute: () => rootRouteImport,
} as any)
const NSlugRoute = NSlugRouteImport.update({
  id: '/n/$slug',
  path: '/n/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/dna': typeof DnaRoute
  '/graph': typeof GraphRoute
  '/holography': typeof HolographyRoute
  '/lab': typeof LabRoute
  '/lattice': typeof LatticeRoute
  '/method': typeof MethodRoute
  '/stop': typeof StopRoute
  '/symmetry': typeof SymmetryRoute
  '/n/$slug': typeof NSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/dna': typeof DnaRoute
  '/graph': typeof GraphRoute
  '/holography': typeof HolographyRoute
  '/lab': typeof LabRoute
  '/lattice': typeof LatticeRoute
  '/method': typeof MethodRoute
  '/stop': typeof StopRoute
  '/symmetry': typeof SymmetryRoute
  '/n/$slug': typeof NSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/dna': typeof DnaRoute
  '/graph': typeof GraphRoute
  '/holography': typeof HolographyRoute
  '/lab': typeof LabRoute
  '/lattice': typeof LatticeRoute
  '/method': typeof MethodRoute
  '/stop': typeof StopRoute
  '/symmetry': typeof SymmetryRoute
  '/n/$slug': typeof NSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/dna'
    | '/graph'
    | '/holography'
    | '/lab'
    | '/lattice'
    | '/method'
    | '/stop'
    | '/symmetry'
    | '/n/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/dna'
    | '/graph'
    | '/holography'
    | '/lab'
    | '/lattice'
    | '/method'
    | '/stop'
    | '/symmetry'
    | '/n/$slug'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/dna'
    | '/graph'
    | '/holography'
    | '/lab'
    | '/lattice'
    | '/method'
    | '/stop'
    | '/symmetry'
    | '/n/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  DnaRoute: typeof DnaRoute
  GraphRoute: typeof GraphRoute
  HolographyRoute: typeof HolographyRoute
  LabRoute: typeof LabRoute
  LatticeRoute: typeof LatticeRoute
  MethodRoute: typeof MethodRoute
  StopRoute: typeof StopRoute
  SymmetryRoute: typeof SymmetryRoute
  NSlugRoute: typeof NSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dna': {
      id: '/dna'
      path: '/dna'
      fullPath: '/dna'
      preLoaderRoute: typeof DnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holography': {
      id: '/holography'
      path: '/holography'
      fullPath: '/holography'
      preLoaderRoute: typeof HolographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lattice': {
      id: '/lattice'
      path: '/lattice'
      fullPath: '/lattice'
      preLoaderRoute: typeof LatticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stop': {
      id: '/stop'
      path: '/stop'
      fullPath: '/stop'
      preLoaderRoute: typeof StopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symmetry': {
      id: '/symmetry'
      path: '/symmetry'
      fullPath: '/symmetry'
      preLoaderRoute: typeof SymmetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n/$slug': {
      id: '/n/$slug'
      path: '/n/$slug'
      fullPath: '/n/$slug'
      preLoaderRoute: typeof NSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  DnaRoute: DnaRoute,
  GraphRoute: GraphRoute,
  HolographyRoute: HolographyRoute,
  LabRoute: LabRoute,
  LatticeRoute: LatticeRoute,
  MethodRoute: MethodRoute,
  StopRoute: StopRoute,
  SymmetryRoute: SymmetryRoute,
  NSlugRoute: NSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
